kind: Deployment
apiVersion: apps/v1
metadata:
   name: rjthelion
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: rjthelion
   template:
      metadata:
        labels:
          app: rjthelion
      spec:
       containers:
        - name: rjthelion
          image: renzdeleon67/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80