kind: Service                             
apiVersion: v1
metadata:
  name: rjthelion
  labels:
    app: rjthelion
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: rjthelion                    
  type: LoadBalancer                   
